env:
  browser: true
  es2021: true

extends:
  - airbnb
  - plugin:react/recommended
  - plugin:functional/recommended
  - plugin:react-hooks/recommended
  - 'prettier'
  - 'plugin:prettier/recommended'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - functional
  - prettier

rules:
  import/extensions: 0
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  react/react-in-jsx-scope: 0
  functional/no-conditional-statements: 0
  functional/no-expression-statements: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statements: 0
  functional/no-throw-statements: 0
  functional/no-return-void: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  react/function-component-definition:
    [2, { 'namedComponents': 'arrow-function' }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
  object-curly-newline: [2, { multiline: true, consistent: true }] # object-curly-newline
  react/jsx-wrap-multilines: [2, { declaration: true, assignment: true, return: true, arrow: true }] # react/jsx-one-expression-per-line
  comma-dangle: [2, { arrays: 'always-multiline', objects: 'always-multiline', imports: 'always-multiline', exports: 'always-multiline', functions: 'ignore' }]
  # Assignment to property of function parameter 'state' 
  # no-param-reassign:
    # [2, { 'props': true, 'ignorePropertyModificationsFor': ['state'] }]


  prettier/prettier: [
      'error',
      {
        'semi': true,
        'singleQuote': true,
        'trailingComma': 'always-multiline', # Aligned with comma-dangle
        'tabWidth': 2,
        'useTabs': false,
        'bracketSpacing': true, # Matches object-curly-newline
        'printWidth': 100,
        'arrowParens': 'always',
        'jsxSingleQuote': true, 
        'proseWrap': 'preserve', # Keeps existing line breaks
      },
    ]